# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vaXYesJMw8ZmbMhcgGZXYM4BZ6K-OMdP
"""

a = [1,2,3,4,5,6,7]
i = int(input())
b = [a[i] for j in range(i)]
print("i-й элемент ряда:",a[i])
print("Список из i элементов равных i:", b)

x = int(input())
y = int(input())
if (x >= -1 and x <= 1) and (y >= -1 and y <= 1): 
  print('Принадлежит')
else: 
  print('Не пренадлежит')

a = [1,2,4,5,6,7,7]
for i in a: 
  if i % 2 == 0:
    print(i, end=' ')

a = [1,2,4,5,6,7,7]
for i in a: 
  if i % 2 == 0:
    print(i, end=' ')

a = int(input())
b = a + 1
c = a - 1
print(f"The next number for the number {a} is {b}. The previous number for the number {a} is {c}.")
